# -*- coding: utf-8 -*-
"""darpg_challenge_r2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hgQX1E96YKexr8kbTuT2JdJNLxGxVXh9
"""

!nvidia-smi

! pip install git+https://github.com/huggingface/transformers -q

from transformers import pipeline

whisper = pipeline('automatic-speech-recognition', model = 'openai/whisper-large-v3',device = 0)

text = whisper('_6267102133.mp3',generate_kwargs={'language':'hindi'})

text

